try{document.execCommand("BackgroundImageCache",!1,!0)}catch(a){}function MkUrlVars(){var a=[],b=location.href.indexOf("?"),c=location.href.lastIndexOf("/");if(-1!=b){for(var e=location.href.substr(b+1,location.href.length),e=e.split("&"),f=0;f<e.length;f++){var g=e[f].split("=");a[g[0]]=g[1]}a[0]=1;a.FileName=location.href.substr(c+1,b-c-1)}else a[0]=-1,a.FileName=location.href.substr(c+1,location.href.length);return a}
function GetRefer(){var a=location.href;0==a.indexOf("http://")&&(a=a.substr(7,a.length));return a.split("/")[0]}
function getPageSize(){var a,b;window.innerHeight&&window.scrollMaxY?(a=document.body.scrollWidth,b=window.innerHeight+window.scrollMaxY):document.body.scrollHeight>document.body.offsetHeight?(a=document.body.scrollWidth,b=document.body.scrollHeight):(a=document.body.offsetWidth,b=document.body.offsetHeight);var c,e;self.innerHeight?(c=self.innerWidth,e=self.innerHeight):document.documentElement&&document.documentElement.clientHeight?(c=document.documentElement.clientWidth,e=document.documentElement.clientHeight):
document.body&&(c=document.body.clientWidth,e=document.body.clientHeight);return[a<c?c:a,b<e?e:b,c,e]}function getPageScroll(){return[self.pageXOffset?self.pageXOffset:document.documentElement&&document.documentElement.scrollLeft?document.documentElement.scrollLeft:document.body.scrollLeft,self.pageYOffset?self.pageYOffset:document.documentElement&&document.documentElement.scrollTop?document.documentElement.scrollTop:document.body.scrollTop]}
function GoTop(a){a.pageYOffset?(alert("1"),a.pageYOffset=0):document.documentElement&&document.documentElement.scrollTop?(alert("2"),document.documentElement.scrollTop=0):document.body&&(alert("3"),document.body.scrollTop=0)}function getPosition(a){for(var b=0,c=0;null!=a;)b+=a.offsetLeft,c+=a.offsetTop,a=a.offsetParent;return[b,c]}
function identifyBrowser(){var a=navigator.userAgent.toLowerCase();if("undefined"!=typeof navigator.vendor&&"KDE"==navigator.vendor&&"undefined"!=typeof window.sidebar)return"kde";if("undefined"!=typeof window.opera){a=parseFloat(a.replace(/.*opera[\/ ]([^ $]+).*/,"$1"));if(7<=a)return"opera7";if(5<=a)return"opera5"}else if("undefined"!=typeof document.all){if("undefined"!=typeof document.getElementById)return a=a.replace(/.*ms(ie[\/ ][^ $]+).*/,"$1").replace(/ /,""),"undefined"!=typeof document.uniqueID?
-1!=a.indexOf("5.5")?a.replace(/(.*5\.5).*/,"$1"):a.replace(/(.*)\..*/,"$1"):"ie5mac"}else if("undefined"!=typeof document.getElementById){if(-1!=navigator.vendor.indexOf("Apple Computer, Inc."))return"undefined"!=typeof window.XMLHttpRequest?"safari1.2":"safari1";if(-1!=a.indexOf("gecko"))return-1!=a.indexOf("chrome")?"chrome":-1!=a.indexOf("firefox")?"firefox":"mozilla"}return!1}
function getEventTarget(a){var b;window.event&&window.event.srcElement?b=window.event.srcElement:a&&a.target&&(b=a.target);for(;0==b.id.length;)b=b.parentNode;return b}function getEventTargetParent(a){var b;window.event&&window.event.srcElement?b=window.event.srcElement:a&&a.target&&(b=a.target);for(;-1==b.id.indexOf("TagArea")&&null!=b.parentNode;)b=b.parentNode;return b}function stopEvent(a){window.event&&window.event.srcElement?event.cancelBubble=!0:a.stopPropagation()}
function stopEvents(a,b){if("undefined"==typeof b||-1==[0,1].indexOf(b))b=2;switch(b){case 0:a.stopPropagation?a.stopPropagation():window.event.cancelBubble=!0;break;case 1:a.preventDefault?a.preventDefault():window.event.returnValue=!1;break;default:a.stopPropagation?(a.stopPropagation(),a.preventDefault()):(window.event.cancelBubble=!0,window.event.returnValue=!1)}try{philosophor.reset()}catch(c){}}
function CalculateTxt(a){for(var b=0,c=0;c<a.length;c++)b=33<=a.charCodeAt(c)&&255>=a.charCodeAt(c)||" "==a.charAt(c)?b+1:b+2;return b}function TextLengthLimit(a,b){for(var c="",e=0,f=b?b:20,g=0;g<a.length;g++)if(e=33<=a.charCodeAt(g)&&255>=a.charCodeAt(g)||" "==a.charAt(g)?e+1:e+2,e<=f)c+=a.charAt(g);else{c+="...";break}return c}
function disableSelection(a){"undefined"!=typeof a.onselectstart?a.onselectstart=function(){return!1}:"undefined"!=typeof a.style.MozUserSelect?a.style.MozUserSelect="none":a.onmousedown=function(){return!1};a.style.cursor="default"}function InputFix(a){a=a.replace(/'/g,"");a=a.stripScripts();return a=a.stripTags()}function trim(a){return a.replace(/^\s*|\s*$/g,"")}
function stripslashes(a){return(a+"").replace(/\\(.?)/g,function(a,c){switch(c){case "\\":return"\\";case "0":return"\x00";case "":return"";default:return c}})}
function fIdCheck(a){var b=(""+a).toLowerCase(),c,e="";if(10!=b.length||!b.match(/[a-z]{2}\d{8}/))return!1;c=b.replace(/([a-z]{2})(\d{7})\d/,"$2");e="abcdefghjklmnpqrstuvxyzio".indexOf(b.charAt(0))+10+(""+("abcdefghjklmnpqrstuvxyzio".indexOf(b.charAt(1))+10)).replace(/.*(\d)$/,"$1")+c;c=0;for(var b=-1,f=e.length;++b<f;)c+=1*e.charAt(b)*(0==b?1:10-b)%10;return 10-(c+"").replace(/.*(\d)$/,"$1")!=a.charAt(9)?!1:!0}
function revertCode(a){a=a.replace(/&amp;/g,"&");a=a.replace(/&lt;/g,"<");a=a.replace(/&gt;/g,">");a=a.replace(/&quot;/g,'"');return a=a.replace(/&#039;/g,"'")}
function trace(a){var b="";"undefined"==typeof TraceEns&&(TraceEns=document.createElement("div"),TraceEns.style.position="absolute",TraceEns.style.left="5px",TraceEns.style.top="5px",TraceEns.style.fontSize="12px",TraceEns.style.width="220px",TraceEns.style.background="#ffffff",TraceEns.style.textAlign="left",TraceEns.style.padding="5px",TraceEns.style.zIndex=1E4,TraceEns.style.display="block",TraceEns.onclick=function(){this.style.display="none"},document.getElementsByTagName("body")[0].appendChild(TraceEns));
if("object"!=typeof a||a instanceof Array)b=a.toString()+"<br>";else for(var c in a)b+=c+": "+a[c]+"<br>";TraceEns.innerHTML+=b;TraceEns.style.display="block"}
function showFlashObject(a,b,c,e,f,g,h){swfUrl="https"==self.window.location.href.substring(0,5)?"https":"http";""==a&&(a="ShockwaveFlash1");""==c&&(c="0");""==e&&(e="0");""==f&&(f="best");g=""==g?"transparent":"";document.write('<OBJECT id="'+a+'" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"');document.write('type="application/x-shockwave-flash" ');document.write('data="'+b+'" ');document.write('codebase="'+swfUrl+'://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab" ');document.write('WIDTH="'+
c+'" HEIGHT="'+e+'">');document.write("<PARAM NAME=menu value=false>");document.write("<PARAM NAME=allowScriptAccess value=always>");document.write('<PARAM NAME=wmode value="'+g+'">');document.write('<PARAM NAME=movie VALUE="'+b+'">');document.write('<PARAM NAME=quality VALUE="'+f+'">');document.write('<PARAM NAME=bgcolor VALUE="'+h+'">');document.write('<embed allowScriptAccess="always" swLiveConnect="true" src="'+b+'" menu="false" quality="'+f+'" wmode="'+g+'" bgcolor="'+h+'" width="'+c+'" height="'+
e+'" type="application/x-shockwave-flash" pluginspace="http://www.macromedia.com/go/getflashplayer" name="'+a+'">');document.write("</OBJECT>")}function mk(a,b){if(!arguments.length)return document.createDocumentFragment();var c=document.createElement(b&&b.tag?b.tag:"div");a&&(c.className=a);if(b){for(i in b.s)c.style[i]=b.s[i];for(i in b.att)c[i]=b.att[i]}return c}
function nodeAppend(a,b){if("undefined"!=typeof a&&"undefined"!=typeof b&&"string"==typeof b&&b.length){var c=document.createDocumentFragment(),e=document.createElement("div");for(e.innerHTML=trim(b);0<e.childNodes.length;)c.appendChild(e.firstChild);a.appendChild(c)}}function recursivelyCollect(a,b){for(var c=[];a=a[b];)1==a.nodeType&&c.push(a);return c}function previousSiblings(a){return recursivelyCollect(a,"previousSibling")}
function nextSiblings(a){return recursivelyCollect(a,"nextSibling")}function mkSelection(a){var b,c;"undefined"!=typeof a.nodeType&&1==a.nodeType&&(/input|textarea/i.test(a.tagName)&&"function"==typeof a.select?a.select():document.body.createTextRange?/input/i.test(a.tagName)?a.select():(b=document.body.createTextRange(),b.moveToElementText(a),b.select()):window.getSelection&&(c=window.getSelection(),b=document.createRange(),b.selectNodeContents(a),c.removeAllRanges(),c.addRange(b)))}
function eTrack(a,b,c){var e="";if("t"==(c||"t")){for(b=b.toLowerCase();null!=a&&(!a.tagName||"body"!=a.tagName.toLowerCase()&&a.tagName.toLowerCase()!=b);)a=a.parentNode;a&&"body"!=a.tagName.toLowerCase()&&"body"!=b&&(e=a)}else{for(c=new RegExp("(^|\\s)"+b+"(\\s|$)");null!=a&&("undefined"==typeof a.className||a.className!=b&&!c.test(a.className));)a=a.parentNode;null==a||"undefined"==typeof a.className||a.className!=b&&!c.test(a.className)||(e=a)}return e}
function tNa(a,b,c){var e={};a=a._event||a;window.event&&window.event.srcElement?(e.a=window.event.type.toLowerCase(),e.t=window.event.srcElement):a&&a.target&&(e.a=a.type.toLowerCase(),e.t=a.target);e.t&&b&&(e.t=eTrack(e.t,b,c));return e}function getIns(a,b){var c=a.Data?a:eTrack(a,b,"c");return c&&"undefined"!=typeof c.Data&&"undefined"!=typeof c.Data.ClassID?window["O"+b][b+c.Data.ClassID]:!1}
function isChild(a,b){var c=!1;if(null!=a&&null!=b&&a!=b)for(;null!=a;){if(a==b){c=!0;break}a=a.parentNode}return c}
function iAct(a){a=tNa(a);switch(a.a.toLowerCase()){case "focus":if(!a.t.getAttribute("data-default"))break;a.t.value==a.t.getAttribute("data-default")&&(a.t.style.color="#666",a.t.value="");break;case "blur":if(!a.t.getAttribute("data-default"))break;if(""==a.t.value)a.t.style.color="#999",a.t.value=a.t.getAttribute("data-default");else{var b=a.t.getAttribute("maxlength")||a.t.value.length;a.t.value=a.t.value.substr(0,Number(b))}}}
function addClass(a,b){if("undefined"!=typeof a&&"undefined"!=typeof b){var c=trim(a.className),e;if(c.length){c=c.split(" ");e=[];for(var f=-1,g=c.length;++f<g;){var h=trim(c[f]);h.length&&h!=b&&e.push(h)}e.push(b);e.length&&(a.className=e.join(" "))}else a.className=b}}
function removeClass(a,b){if("undefined"!=typeof a&&"undefined"!=typeof b){var c=trim(a.className),e;if(c.length){c=c.split(" ");e=[];for(var f=-1,g=c.length;++f<g;){var h=trim(c[f]);h.length&&h!=b&&e.push(h)}a.className=e.join(" ")}}}function pointer(a){var b=[];window.event?(a=getPageScroll(),b=[window.event.x+a[0],window.event.y+a[1]]):b=[a.pageX,a.pageY];return b}
function createCSSClass(a,b,c){if(document.styleSheets&&0!=document.getElementsByTagName("head").length){var e,f,g=!1;"undefined"!=typeof c&&c&&("undefined"!=typeof c.sheet?(e=c.sheet,f=typeof e.media,g=!0):(c=document.createElement("style"),c.type="text/css",document.getElementsByTagName("head")[0].appendChild(c),c.usable=!0,navigator.ssHost=document.styleSheets[document.styleSheets.length-1]));if(!g)if(navigator.ssHost)e=navigator.ssHost,f=typeof e.media;else{g=-1;for(c=document.styleSheets.length;++g<
c;){var h=document.styleSheets[g],k,m,l;if(!h.disabled&&("undefined"==typeof h.usable||h.usable)){k=h.media;f=typeof k;"undefined"==typeof h.usable&&(h.usable=!1);if("string"==f){try{m=null==h.rules?!0:!1}catch(n){m=!0}""!=k&&-1==k.indexOf("screen")||m||(e=h,h.usable=!0)}else if("object"==f){try{m=null==h.cssRules?!0:!1,l=k.mediaText}catch(n){m=!0}m||"undefined"==typeof l||""!=l&&-1==l.indexOf("screen")||(e=h,h.usable=!0)}if("undefined"!=typeof e)break}}if("undefined"==typeof e){c=document.createElement("style");
c.type="text/css";document.getElementsByTagName("head")[0].appendChild(c);g=-1;for(c=document.styleSheets.length;++g<c;)h=document.styleSheets[g],h.disabled||"undefined"!=typeof h.usable&&!h.usable||(h.usable=!0,e=h);f=typeof e.media}navigator.ssHost=e}if("string"==f){g=-1;for(c=e.rules.length;++g<c;)if(e.rules[g].selectorText&&e.rules[g].selectorText.toLowerCase()==a.toLowerCase()){e.rules[g].style.cssText=b;return}e.addRule(a,b)}else if("object"==f){g=-1;for(c=e.cssRules.length;++g<c;)if(e.cssRules[g].selectorText&&
e.cssRules[g].selectorText.toLowerCase()==a.toLowerCase()){e.cssRules[g].style.cssText=b;return}e.insertRule(a+"{"+b+"}",0)}}}
function getValue(a,b,c){if("undefined"!=typeof a){var e=["button","file","image","reset","submit"],f=HO(),g=[],h=["input","textarea","select"],e=["button","file","image","reset","submit"],k="s";"undefined"!=typeof c&&(f={},k="o");c=0;for(var m=h.length;c<m;c++){var l=AO(a.getElementsByTagName(h[c]));0<l.length&&(g=g.concat(l))}c=0;for(m=g.length;c<m;c++)if(l=g[c],l.type&&l.name&&-1==e.indexOf(l.type))switch(l.type){case "radio":f[l.name]||(f[l.name]="");l.checked&&(f[l.name]=l.value);break;default:if("checkbox"==
l.type)if(a=l.name.replace(/(.*)\[\]/,"$1"),-1!=l.name.indexOf("[]")){if(!f[a]||!f[a]instanceof Array)f[a]=[];f[a].push(l.checked?l.value:"")}else f[a]=l.checked?l.value:"";else f[l.name]=l.getAttribute("data-default")&&l.value==l.getAttribute("data-default")?"":l.value}if("undefined"!=typeof b)for(c in b)f[c]=b[c];return"s"==k?f.toQueryString():f}}
function inspects(a,b){var c=[],e=["input","textarea","select","button"],f={},g=b||{},h={s:!0},k={};if("undefined"==typeof a)h={s:!1,e:"form",t:0};else{for(var m=-1,l=e.length;++m<l;)$A(a.getElementsByTagName(e[m])).each(function(a){a.type&&"hidden"==a.type||!a.name||!g[a.name]||(k[a.name]||(k[a.name]=[]),k[a.name].push(a))});for(m in g){var n=k[m];if("undefined"!=typeof n)for(var t=-1,l=n.length;++t<l;)c.push(n[t])}e=["checkbox","radio"];m=0;for(l=c.length;m<l;m++){var n=c[m],v;if((!n.type||"hidden"!=
n.type)&&n.name&&g[n.name]){if(-1!=e.indexOf(n.type))"undefined"==typeof f[n.name]&&(f[n.name]={e:n,d:[]}),n.checked&&0<n.value.length&&f[n.name].d.push(n.value);else if(0==n.value.length||n.value==n.getAttribute("data-default"))v=0;else{g[n.name][0]=new RegExp("^.{1,"+g[n.name][0]+"}$","m");for(var q=g[n.name],t=0;t<q.length;t++)if("function"==typeof q[t]){var u=q[t](n.value);if(u&&0<u.length){v=u;break}}else if(!n.value.match(q[t])){v=0==t?1:2;break}}if("undefined"!=typeof v){h={s:!1,t:v,e:n};break}}}for(m in f)if(0==
f[m].d.length){h={s:!1,t:0,e:f[m].e};break}}return h}function testConnection(a){var b,c=!1;a=a||"/status.html";if(window.XMLHttpRequest)b=new XMLHttpRequest,b.overrideMimeType&&b.overrideMimeType("text/xml");else if(window.ActiveXObject)try{b=new ActiveXObject("Msxml2.XMLHTTP")}catch(e){try{b=new ActiveXObject("Microsoft.XMLHTTP")}catch(f){}}if("undefined"==typeof b)return!0;b.open("HEAD",a,!1);try{b.send(),c="undefned"!=typeof b.status&&200!=b.status?!1:!0}catch(e){c=!1}return c}
function getURIs(a){var b={},c=a||location.href;uri=c;a=[uri.replace(/.*\?([^\#]*)(\#[^\#]*)*$/,"$1"),uri.replace(/([^\#\!]*)\#\!([^\#\!]*)$/,"$2")];for(var e=-1,f=a.length;++e<f;)if(a[e]!=uri)for(var g=a[e].split("&"),h=-1,k=g.length;++h<k;)if(-1!=g[h].indexOf("=")){var m=g[h].split("=");b[m[0]]=m[1]}return[c.replace(/^([^\?]*)\??.*$/,"$1").replace(/^([^\#]*)\#?.*$/,"$1"),b]}
function parseUrl(a){var b={},c="";b.protocol=/^https/i.test(a)?"https:":"http:";b.host=/^(https?):\/\/([^\/]*)\/(.*)/.test(a)?a.replace(/^(https?):\/\/([^\/]*)\/(.*)/,"$2"):a.replace(/^(https?):\/\/(.*)/,"$2");c=a.replace(b.protocol+"//"+b.host,"");c.length&&(c=c.replace(/^\/(.*)/,"$1"));c.length&&(b.path=c.replace(/([^\?]*)\?(.*)/,"$1"),b.path.length&&(b.path="/"+b.path.replace(/(.*)\/$/,"$1")),/([^\?]*)\?(.*)/.test(c)&&(b.query=c.replace(/.*\?([^\#]*)(\#[^\#]*)*$/,"$1"),b.fragment=c.replace(/([^\#\!]*)\#\!([^\#\!]*)$/,
"$2"),b.fragment==c&&delete b.fragment));return b}function nnpCheck(a,b){for(var c=!0,e=-1,f=a.length;++e<f;)"undefined"==typeof b[a[e]]&&(c=!1);return c}function empty(a){for(;a.childNodes.length;)a.removeChild(a.firstChild)}function purge(a){if("object"==typeof a)for(var b in a){try{a[b]=arguments.callee(a[b])}catch(c){a[b]=null}a[b]instanceof Array&&(a[b]=null)}else a=null;return a}function isEmptyObject(a){for(var b in a)return!1;return!0}
function clone(a){var b;if(a instanceof Array)b=a.concat();else{b={};for(var c in a)b[c]=a[c]}return b}function SelectionSwitch(a){var b=document.getElementsByTagName("body")[0];switch(a){case "Disable":b.onselectstart=function(){return!1};b.style.MozUserSelect="none";b.onmousedown=function(){return!1};break;default:b.onselectstart=function(){return!0},b.style.MozUserSelect="block",b.onmousedown=null}}
function getStyle(a,b){var c="";"undefined"!=typeof a.style&&a.style[b]?c=a.style[b]:a.currentStyle?c=a.currentStyle[camelCase(b)]:window.getComputedStyle&&(c=document.defaultView.getComputedStyle(a,null).getPropertyValue(b.replace(/([A-Z])/g,"-$1").toLowerCase()));void 0==c&&(c=1);return c}
function getSize(a){var b=getStyle(a,"display");if(b&&"none"!=b)a=[a.offsetWidth,a.offsetHeight];else{var b=a.style,c={visibility:b.visibility,position:b.position,display:b.display},e={visibility:"hidden",display:"block"};"fixed"!==c.position&&(e.position="absolute");for(var f in e)b[f]=e[f];a=[a.offsetWidth,a.offsetHeight];for(f in c)b[f]=c[f]}return a}function getKeyCode(a){var b;window.event&&window.event.srcElement?b=window.event.keyCode:a&&a.target&&(b=a.keyCode);return b}
function dataURItoBlob(a){var b=-1!=a.split(",")[0].indexOf("base64")?atob(a.split(",")[1]):decodeURIComponent(a.split(",")[1]);a=a.split(",")[0].split(":")[1].split(";")[0];for(var c=new ArrayBuffer(b.length),e=new Uint8Array(c),f=-1,g=b.length;++f<g;)e[f]=b.charCodeAt(f);window.Blob?b=new Blob([e],{type:a}):(b=new (window.MozBlobBuilder||window.WebKitBlobBuilder||window.BlobBuilder),b.append(c),b=b.getBlob(a));return b}function extend(a,b){for(var c in b)a[c]=b[c];return a}
function _createResponder(a,b){return function(c){extend(c,{target:c.srcElement||a});b.call(a,c)}}function observe(a,b,c){for(var e=-1,f=arguments.length;++e<f;)if("undfefined"==typeof arguments[e])return;if("function"==typeof c){var g=a.addEventListener?!0:!1,h;h=a instanceof Array?a:[a];e=-1;for(f=h.length;++e<f;){var k=_createResponder(h[e],c);g?h[e].addEventListener(b,k,!1):h[e].attachEvent("on"+b,k)}}}
function stopObserving(a,b,c){for(var e=-1,f=arguments.length;++e<f;)if("undfefined"==typeof arguments[e])return;if("undefined"==typeof c)try{delete a["on"+b]}catch(k){}else if("function"==typeof c){var g=a.removeEventListener?!0:!1,h;h=a instanceof Array?a:[a];e=-1;for(f=h.length;++e<f;)g?h[e].removeEventListener(b,c,!1):h[e].detachEvent("on"+b,c)}}
function fireEvent(a,b){if("undefined"!=typeof a){var c=/^click|mouse(down|up|over|out|move)$/i.test(b)?"MouseEvents":"HTMLEvents",e,f,g=!0;e={pointerX:0,pointerY:0,button:0,ctrlKey:!1,altKey:!1,shiftKey:!1,metaKey:!1,bubbles:!0,cancelable:!0};if(document.createEvent)f=document.createEvent(c),"HTMLEvents"==c?f.initEvent(b,e.bubbles,e.cancelable):f.initMouseEvent(b,e.bubbles,e.cancelable,document.defaultView,e.button,e.pointerX,e.pointerY,e.pointerX,e.pointerY,e.ctrlKey,e.altKey,e.shiftKey,e.metaKey,
e.button,a),a.dispatchEvent(f);else if(document.createEventObject){e.clientX=e.pointerX;e.clientY=e.pointerY;f=document.createEventObject();for(var h in e)f[h]=e[h];a.fireEvent("on"+b,f)}else g=!1;return g}}function isMobile(){return isEventSupported("touchstart")?"touch":navigator.msPointerEnabled&&navigator.msMaxTouchPoints&&1<navigator.msMaxTouchPoints?"pointer":!1}
function pursuer(){return isEventSupported("touchstart")?{down:"touchstart",move:"touchmove",up:"touchend"}:"undefined"!=typeof navigator.msPointerEnabled&&navigator.msPointerEnabled?{down:"MSPointerDown",move:"MSPointerMove",up:"MSPointerUp"}:{down:"mousedown",move:"mousemove",up:"mouseup"}}
function detectFlash(){var a,b=navigator.userAgent,c,e;if(null!=navigator.plugins&&0<navigator.plugins.length&&(navigator.plugins["Shockwave Flash 2.0"]||navigator.plugins["Shockwave Flash"]))a=navigator.plugins["Shockwave Flash 2.0"]?" 2.0":"",a=navigator.plugins["Shockwave Flash"+a].description,b=a.split(" "),c=b[2].split("."),a=[],a.push(c[0]),a.push(c[1]),b=""!=b[3]?b[3].split("r"):b[4].split("r"),a.push(0<b[1]?b[1]:0);else if(/webtv\/2.6/i.test(b))a=[4];else if(/webtv\/2.5/i.test(b))a=[3];else if(/webtv/.test(b))a=
[2];else if(/win/i.test(navigator.appVersion)&&/.*msie.*/i.test(detectMSB())){try{e=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7"),c=e.GetVariable("$version")}catch(f){}if(!c)try{e=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"),c="WIN 6,0,21,0",e.AllowScriptAccess="always",c=e.GetVariable("$version")}catch(f){}if(!c)try{e=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.3"),c=e.GetVariable("$version")}catch(f){}if(!c)try{new ActiveXObject("ShockwaveFlash.ShockwaveFlash.3"),c="WIN 3,0,18,0"}catch(f){}if(!c)try{new ActiveXObject("ShockwaveFlash.ShockwaveFlash"),
c="WIN 2,0,0,11"}catch(f){c=-1}-1!=c&&(a=c.replace(/win\s*(.*)/i,"$1").split(","))}return a}
function detectMSB(){createCSSClass(".detect4MSB","position:relative;font-size:0px;left:-100px;top:-1px;height:1px;width:100px;width:10px\\9;*width:7px;_width:6px;");var a=mk("detect4MSB"),b="others",c;document.body.appendChild(a);c=getStyle(a,"width").toLowerCase();switch(c){case "6px":b="msie6";break;case "7px":b="msie7";break;case "10px":c=!0;try{createCSSClass(":root .detect4MSB","width:200px;")}catch(e){c=!1}b=c?"msie"+("10px"==getStyle(a,"width").toLowerCase()?"8":""):"msie8";default:isCSSSupport("-ms-user-select")&&
(b="msie")}document.body.removeChild(a);createCSSClass(".detect4MSB","");try{createCSSClass(":root .detect4MSB","")}catch(e){}return b}function isMQSupport(){try{createCSSClass("@media all","#mqe{width:100px;}")}catch(c){}var a=mk("",{att:{id:"mqe"}}),b;document.body.appendChild(a);b=getStyle(a,"width").toLowerCase();document.body.removeChild(a);return"100px"===b}
function isAniSupport(){for(var a=["webkit","","moz","o","ms"],b,c=-1,e=a.length;++c<e;){var f=a[c]?"-":"",g,h,k,m,l,n;g=f+a[c]+f+"transform";h=f+a[c]+f+"transition";k=f+a[c]+f+"keyframes";m=f+a[c]+f+"animation";l=f+a[c]+f+"perspective";n=f+a[c]+f+"animate-timing-function";o=f+a[c]+f+"transform-origin";s=f+a[c]+f+"transform-style";d=f+a[c]+f+"transition-delay";du=f+a[c]+f+"transition-duration";if(isCSSSupport(g)&&isCSSSupport(h)){b={};b.transform=g;b.transition=h;b.keyframes=k;b.animation=m;b.perspective=
l;b.aniTimeFunc=n;b.origin=o;b.transformStyle=s;b.delay=d;b.duration=du;break}}b&&(b.eventAnimationend=b.transform.match(/webkit/i)?"webkitAnimationEnd":"animationend",b.eventTransition=b.transform.match(/webkit/i)?"webkitTransitionEnd":"transitionend");return b}
function supportsWebComponents(){for(var a={ShadowDOM:!1,CustomElements:!1},b=["","webkit","moz","o","ms"],c="createShadowRoot",e=mk(""),f=-1,g=b.length;++f<g;){var h=b[f]+(b[f]?capitalize(c):c);if(e[h]){a.ShadowDOM=h;break}}a.template="content"in document.createElement("template");a.imports="import"in document.createElement("link");c="register";f=-1;for(g=b.length;++f<g;)if(h=b[f]+(b[f]?capitalize(c):c),document[h]){a.CustomElements=h;break}c="registerElement";f=-1;for(g=b.length;++f<g;)if(h=b[f]+
(b[f]?capitalize(c):c),document[h]){a.CustomElements=h;break}a.cssShadow=!0;try{createCSSClass("div::shadow q","background:transparent;")}catch(k){a.cssShadow=!1}a.cssDeep=!0;try{createCSSClass("div /deep/ q","background:transparent;")}catch(k){a.cssDeep=!1}a.pseudo=!0;try{createCSSClass("div::x-q","background:transparent;")}catch(k){a.pseudo=!1}a.cssCat=!0;try{createCSSClass("div^^q","background:transparent;")}catch(k){a.cssCat=!1}a.cssHat=!0;try{createCSSClass("div^q","background:transparent;")}catch(k){a.cssHat=
!1}return a}function isEventSupported(a,b){var c=mk(""),e="on"+a,f;b&&(c=b.tagName?b.cloneNode(!0):b);f=e in c;if(!f&&c.setAttribute){if("focusin"==a)return c=mk("",{tag:"a",att:{href:"#"},s:{position:"fixed",top:"0"}}),e=function(){f=!0},c.addEventListener?c.addEventListener("focusin",e):c.onfocusin=e,document.body.appendChild(c).focus(),document.body.removeChild(c),f;c.setAttribute(e,"");f="function"==typeof c[e];"undefined"!=typeof c[e]&&(c[e]=null);c.removeAttribute(e)}c=null;return f}
function isCSSSupport(a,b){var c=mk("");a=/^-ms/.test(a)?"ms"+camelCase(a.replace(/-ms/,"")):camelCase(a);b&&b.tagName&&(c=b.cloneNode(!0));return a in c.style}function isAPISupport(a,b){for(var c=b||window,e=["","webkit","moz","o","ms"],f="",g=-1,h=e.length;++g<h;){var k=e[g]+(e[g]?capitalize(a):a);if(c[k]){f=c[k];break}}return f}function fcamelCase(a,b){return b.toUpperCase()}function camelCase(a){return a.replace(/-([a-z])/ig,fcamelCase)}
function capitalize(a){return a.replace(/^[a-z]{1}/,function(a){return a.toLocaleUpperCase()})}function getRand(a,b){return Math.floor(Math.random()*(b-a+1)+a)}function d2h(a){return a.toString(16)}function h2d(a){return parseInt(a,16)}
function addLoadListener(a){if("undefined"!=typeof window.addEventListener)window.addEventListener("load",a,!1);else if("undefined"!=typeof document.addEventListener)document.addEventListener("load",a,!1);else if("undefined"!=typeof window.attachEvent)window.attachEvent("onload",a);else{var b=window.onload;window.onload="function"!=typeof window.onload?a:function(){b();a()}}}Array.prototype.indexOf||(Array.prototype.indexOf=function(a){for(var b=0;b<this.length;b++)if(this[b]==a)return b;return-1});
Array.prototype.lastIndexOf||(Array.prototype.lastIndexOf=function(a){for(var b=this.length-1;0<=b;b--)if(this[b]==a)return b;return-1});Array.prototype.each||(Array.prototype.each=function(a){for(var b=-1,c=this.length;++b<c;)a(this[b],b)});Array.prototype.without||(Array.prototype.without=function(){for(var a=[],b=[],c=-1,e=arguments.length;++c<e;)a.push(arguments[c]);c=-1;for(e=this.length;++c<e;)-1==a.indexOf(this[c])&&b.push(this[c]);return b});"object"!==typeof JSON&&(JSON={});
(function(){function a(a){return 10>a?"0"+a:a}function b(a){f.lastIndex=0;return f.test(a)?'"'+a.replace(f,function(a){var b=k[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function c(a,e){var f,k,q,u,w=g,r,p=e[a];p&&"object"===typeof p&&"function"===typeof p.toJSON&&(p=p.toJSON(a));"function"===typeof m&&(p=m.call(e,a,p));switch(typeof p){case "string":return b(p);case "number":return isFinite(p)?String(p):"null";case "boolean":case "null":return String(p);
case "object":if(!p)return"null";g+=h;r=[];if("[object Array]"===Object.prototype.toString.apply(p)){u=p.length;for(f=0;f<u;f+=1)r[f]=c(f,p)||"null";q=0===r.length?"[]":g?"[\n"+g+r.join(",\n"+g)+"\n"+w+"]":"["+r.join(",")+"]";g=w;return q}if(m&&"object"===typeof m)for(u=m.length,f=0;f<u;f+=1)"string"===typeof m[f]&&(k=m[f],(q=c(k,p))&&r.push(b(k)+(g?": ":":")+q));else for(k in p)Object.prototype.hasOwnProperty.call(p,k)&&(q=c(k,p))&&r.push(b(k)+(g?": ":":")+q);q=0===r.length?"{}":g?"{\n"+g+r.join(",\n"+
g)+"\n"+w+"}":"{"+r.join(",")+"}";g=w;return q}}"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()});var e=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
f=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,g,h,k={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},m;"function"!==typeof JSON.stringify&&(JSON.stringify=function(a,b,e){var f;h=g="";if("number"===typeof e)for(f=0;f<e;f+=1)h+=" ";else"string"===typeof e&&(h=e);if((m=b)&&"function"!==typeof b&&("object"!==typeof b||"number"!==typeof b.length))throw Error("JSON.stringify");return c("",{"":a})});
"function"!==typeof JSON.parse&&(JSON.parse=function(a,b){function c(a,e){var f,g,h=a[e];if(h&&"object"===typeof h)for(f in h)Object.prototype.hasOwnProperty.call(h,f)&&(g=c(h,f),void 0!==g?h[f]=g:delete h[f]);return b.call(a,e,h)}var f;a=String(a);e.lastIndex=0;e.test(a)&&(a=a.replace(e,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return f=eval("("+a+")"),"function"===typeof b?c({"":f},""):f;throw new SyntaxError("JSON.parse");})})();window.requestAnimationFrame=window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame;window.cancelAnimationFrame=window.cancelAnimationFrame||window.cancelAnimationFrame||window.cancelAnimationFrame||window.cancelAnimationFrame||window.cancelAnimationFrame;
window.requestAnimationFrame||(RAFlastTime=0,window.requestAnimationFrame=function(a){var b=(new Date).getTime(),c=Math.max(0,16-(b-RAFlastTime)),e;e=window.setTimeout(function(){a(b+c)},c);RAFlastTime=b+c;return e});window.cancelAnimationFrame||(window.cancelAnimationFrame=function(a){clearTimeout(a)});"undefined"==typeof window.performance&&(performance={timing:{},now:function(){return(new Date).getTime()}});
"function"!=typeof performance.mark&&(performance.marks={},performance.measures={},"function"!=typeof performance.now&&(performance.now=function(){return(new Date).getTime()}),performance.mark=function(a){performance.marks[a]={duration:0,startTime:this.now(),entryType:"mark",name:a}},performance.measure=function(a,b,c){this.marks[b]&&this.marks[c]&&(performance.measures[a]={duration:this.marks[c].startTime-this.marks[b].startTime,startTime:this.marks[b].startTime,entryType:"measure",name:a})},performance.getEntriesByName=
function(a){var b=[];this.measures[a]&&null!=this.measures[a]&&b.push(this.measures[a]);this.marks[a]&&null!=this.marks[a]&&b.push(this.marks[a]);return b},performance.getEntriesByType=function(a){var b=[];if("undefined"!=typeof a&&-1!=["mark","measure"].indexOf(a)){a+="s";for(var c in this[a])null!=this[a][c]&&b.push(clone(this[a][c]))}return b},performance.clearMarks=function(a){"undefined"==typeof a?(purge(this.marks),this.marks={}):this.marks[a]&&(purge(this.marks[a]),this.marks[a]=null)},performance.clearMeasures=
function(a){"undefined"==typeof a?(purge(this.measures),this.measures={}):this.measures[a]&&(purge(this.measures[a]),this.measures[a]=null)});
var measures={get:function(a){var b=document.cookie.replace(/ /g,"").split(";"),c;if(b.length)for(var e=-1,f=b.length;++e<f;){var g=b[e].split("=");if(g[0]==a){c=g[1];break}}return c},set:function(a,b){var c=!0,e=(new Date).getTime()+864E5,e=new Date(e);try{document.cookie=a+"="+b+";path=/;expires="+e.toUTCString()}catch(f){c=!1}c&&this.get(a)!=b&&(c=!1);return c},remove:function(a){var b=new Date;b.setDate(b.getDate()-10);document.cookie=a+"=;path=/;expires="+b.toUTCString()},showLog:function(a){var b=
0,c=0;trace("Measure Result:");trace("------------------------------------------------------");for(var b=Number(this.get(a)),e=0,f=b+1;++e<f;){var g=a+"_"+e,h=Number(this.get(g));trace("sample_"+e+": "+h+" ms");c+=h;this.remove(g)}trace("------------------------------------------------------");trace("Average: "+c/b+" ms");trace("");this.remove(a)},init:function(a,b){var c=Number(this.get(a))||0,e,f;if(c>=(b||10))this.showLog(a);else{e=performance.getEntriesByType("measure");for(var g=-1,h=e.length;++g<
h;){var k=e[g];if(k.name==a){f=k.duration;break}}f&&(c+=1,this.set(a,c),this.set(a+"_"+c,f),location.reload())}}};function AO(a){var b=[];if(a)for(var c=0,e=a.length;c<e;c++)b.push(a[c]);return b}function HO(a){return a instanceof HashObj?a:new HashObj(a)}function HashObj(a){this.Constructor(a)}
HashObj.prototype={toQueryString:function(){var a=[],b;for(b in this)if("function"!=typeof this[b]){var c=[this[b]],e="";if(this[b]instanceof Array){for(var e="[]",c=[],f=0,g=this[b].length;f<g;f++)this[b][f]&&c.push(this[b][f]);0==c.length&&c.push("")}for(f=0;f<c.length;f++)a.push(encodeURIComponent(b)+e+"="+encodeURIComponent(c[f]))}return a.join("&")},Constructor:function(a){if("undefined"!=typeof a)for(var b in a)this[b]=a[b]}};/*programed by mei(李維翰), http://www.facebook.com/mei.studio.li*/